"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$username\
$container\
$docker_context\
$nodejs\
$python\
$rust\
$aws
$sudo\
$git_state\
$git_status\
($jobs$container$git_metrics)\
$character
"""

right_format = """
$cmd_duration\
$battery\
$status
"""

continuation_prompt = "[â–¸â–¹ ](dimmed white)"

add_newline = true
palette = 'tokyonight'

[palettes.tokyonight]
color_fg0 = "#c0caf5"
color_bg1 = "#1f2335"
color_bg2 = "#414868"
color_blue = "#7aa2f7"
color_aqua = "#7dcfff"
color_green = "#c3e88d"
color_orange = "#ff9e64"
color_purple = "#bb9af7"
color_red = "#ff007c"
color_yellow = "#ffc777"

[character]
format = "$symbol "
success_symbol = '[ï² ](bold fg:color_green)'
error_symbol = '[ï² ](bold fg:color_red)'
vimcmd_symbol = '[ï´ ](bold fg:color_yellow)'
vimcmd_replace_one_symbol = '[ï´ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ï´ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ï´ ](bold fg:color_yellow)'


# Segment configurations
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'îŒ½  '

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "â–ˆ"
charging_symbol = "[â†‘](italic bold fg:color_green)"
discharging_symbol = "â†“"
unknown_symbol = "â–‘"
empty_symbol = "â–ƒ"

[[battery.display]]
threshold = 20
style = "italic bold fg:color_red"

[[battery.display]]
threshold = 60
style = "italic dimmed fg:color_purple"

[[battery.display]]
threshold = 70
style = "italic dimmed fg:color_yellow"

[cmd_duration]
style = "italic fg:color_white"
format = "[â—„ $duration ]($style)"

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
use_os_path_sep = true
read_only = " ó°Œ¾"
style = "fg:color_blue"
format = "[ $path ]($style)[$read_only]($read_only_style)"
repo_root_style = "fg:color_aqua bold"
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)\
"""

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[docker_context]
symbol = "ïŒˆ "
format = 'via [ğŸ‹ $context](blue bold)'

[git_branch]
symbol = "ï˜ "
style = "italic fg:color_red"
format = '[ [$symbol](fg:color_aqua) $branch(:$remote_branch) ]($style)'
truncation_symbol = "â‹¯"
truncation_length = 11

[git_commit]
tag_symbol = ' ï’ '

[git_metrics]
disabled = false
format = '([â–´$added]($added_style) )([â–¿$deleted]($deleted_style) )'
added_style = 'italic dimmed fg:color_green'
deleted_style = 'italic dimmed fg:color_red'
ignore_submodules = true

[git_status]
style = "bold italic fg:color_yellow"
format = '[($all_status$ahead_behind )]($style)'

[hostname]
ssh_symbol = "î¬ "

[jobs]
style = "fg:color_white"
symbol = "[â–¶](fg:color_blue italic)"
format = "[$symbol$number]($style) "

[nodejs]
symbol = "îœ˜ "
format = 'via [ğŸ¤– $version](bold green) '

[os]
disabled = false
style = "fg:color_fg0"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[package]
symbol = "ó°— "
format = 'via [ğŸ $version](208 bold) '

[python]
symbol = "îˆµ "

[rust]
symbol = "ó±˜— "

[sudo]
disabled = false
style = "bold fg:color_blue"
format = "[$symbol]($style)"

[time]
style = "italic dimmed fg:color_white"
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"

[username]
show_always = false
style_user = "fg:color_yellow bold italic"
style_root = "fg:color_purple bold italic"
format = '[ $user ]($style)'
